name: tododok
description: "모바일 환경에서 한글과 영문 타자 실력을 재미있게 기를 수 있는 타자 연습 어플"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # UI Framework
  cupertino_icons: ^1.0.8

  # State Management
  riverpod_annotation: ^2.6.1

  # Data Classes & Code Generation
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # Routing
  hooks_riverpod: ^2.6.1
  go_router: ^15.1.1

  # Firebase
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  firebase_storage: ^12.4.6
  firebase_messaging: ^15.2.5

  # Time & Date
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.2
  freezed: ^3.0.6
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true